spring.application.name=spring-app-duoc
server.port=8080

# OpenAPI / Swagger UI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Logging
logging.level.cl.duoc.springappduoc=INFO
